name: Hello world 
on: workflow_dispatch
jobs:
   hello:
      runs-on: ubuntu-22.04
      steps:
         - name: Hello step
           run: |
              echo "This is first line"
              echo "This is second line"
